# Generated by Django 4.1.2 on 2022-10-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0003_alter_profile_birth_date_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
