# Generated by Django 4.1.2 on 2022-10-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0007_remove_user_profile_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
